import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
}

android {
    namespace 'com.project.ianime'
    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        applicationId "com.project.ianime"
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()
        versionCode 1
        versionName "1.0"
        buildConfigField("String", "API_BASE_PATH", apiBasePath)
        buildConfigField("String", "API_KEY", apiKey)

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
        buildConfig true
        compose true
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
    }
}

dependencies {
    // AndroidX / Material
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.google.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.recyclerview
    implementation libs.androidx.swiperefreshlayout
    implementation libs.androidx.fragment.ktx
    implementation libs.bundles.lifecycle

    // Compose
    implementation platform(libs.androidx.compose.bom)
    implementation libs.bundles.compose
    debugImplementation libs.androidx.compose.ui.tooling

    // Network
    implementation libs.bundles.retrofit

    // RxJava
    implementation libs.bundles.rx

    // Hilt
    implementation libs.hilt.android
    ksp libs.hilt.compiler

    // Images
    implementation libs.picasso
    implementation libs.bundles.coil

    // Room
    implementation libs.bundles.room
    ksp libs.room.compiler

    // Test
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.androidx.test.espresso
    androidTestImplementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.androidx.compose.ui.test.junit4
    debugImplementation libs.androidx.compose.ui.test.manifest
}
